server:
  port: 8082

spring:
  application:
    name: steiner
  profiles:
    active: dev
    include: drsMock #,liquibaseActive
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    hikari:
      leak-detection-threshold: 10000
      maximum-pool-size: 20
      minimumIdle: 4
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
    open-in-view: true


  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail-on-empty-beans: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  http:
    multipart:
      max-file-size: 50Mb    #DRSStoreResponse-limit
      max-request-size: 50Mb
  h2:
    console:
      enabled: true
      path: /h2
      #DRSStoreResponse-limit

info:
    project:
        version: #project.version#
logging:
  level:
    ROOT: INFO
    com.zaxxer.hikari: debug
  pattern:
    console: "[%date] [%level] [%X{THREAD_ID}] [%X{correlationId}] [%X{UUID}] [%X{TRANSACTION_ID}] [%X{SOURCE_IP}] [%X{HTTP_REQ_METHOD}] [%X{ENDPOINT}] [%X{SOAP_ACTION}] [%X{HTTP_RESP_CODE}] [%logger{10}] [%file:%line] [><[%msg]><] [%ex{full}]%n"

application:
  security: jwt

security:
  basic:
    enabled: false
log:
    pattern: "[%date] [%level] [%X{THREAD_ID}] [%X{correlationId}] [%X{UUID}] [%X{TRANSACTION_ID}] [%X{SOURCE_IP}] [%X{HTTP_REQ_METHOD}] [%X{ENDPOINT}] [%X{SOAP_ACTION}] [%X{HTTP_RESP_CODE}] [%logger{10}] [%file:%line] [><[%msg]><] [%ex{full}]%n"

#the following setup is optional
queue-props:
  url: "amqp://localhost:5672/%2f"
  username: "rabbitmq"
  password: "rabbitmq"
  topicName: "documents-topic"