package com.arise.steiner.errors;

public enum ErrorKey {
    UNEXPECTED,
    ENTITY_NOT_FOUND,
    INVALID_CREDENTIALS,
    BUSINESS_LOGIC_INVALID,
    EMTPY_BYTES,
    FILE_WITHOUT_NAME,
    NO_DOCUMENT_FOUND, FILE_NOT_FOUND_LOCALLY, MALFORMED_URL, NULL_PARAMS, MISSING_GRAPHQL_KEY, INVALID_TYPE_CAST;
}
